include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true
    prefer_single_quotes: true
    prefer_const_constructors: false # TOTO remove before release
    prefer_const_literals_to_create_immutables: false  # TOTO remove before release