name: serv_expert_webclient
description: Serve expert client application.
publish_to: 'none'
version: 1.0.16+16

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  cloud_functions: ^4.0.7
  firebase_messaging: ^14.2.1
  
  flutter_riverpod: ^2.1.1
  auto_route: ^5.0.4
  equatable: ^2.0.5
  pinput: ^2.2.23
  get_storage: ^2.0.3

  flutter_fadein: ^2.0.0
  flutter_svg: ^2.0.0+1
  transparent_image: ^2.0.1
  hand_signature: ^3.0.1
  dio: ^5.2.1
  dio_smart_retry: ^5.0.0
  universal_html: ^2.2.1
  http: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  auto_route_generator: ^5.0.3




flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/

