// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB93WmA8tpixMljBtBid6ITuXcjvXIvWMA',
    appId: '1:249654500838:web:c39c2ab87a1eac41614a27',
    messagingSenderId: '249654500838',
    projectId: 'servexpert-cd5cf',
    authDomain: 'servexpert-cd5cf.firebaseapp.com',
    storageBucket: 'servexpert-cd5cf.appspot.com',
    measurementId: 'G-BD91EYS3HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY7BsD4Nnecwv3L0_s3JpkXIRqQ68Fhgk',
    appId: '1:249654500838:android:dc4f3da39ac38729614a27',
    messagingSenderId: '249654500838',
    projectId: 'servexpert-cd5cf',
    storageBucket: 'servexpert-cd5cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmSUW179OYIL96fg4OaEoNXrkusmypeAM',
    appId: '1:249654500838:ios:42e372d76e8a8e3c614a27',
    messagingSenderId: '249654500838',
    projectId: 'servexpert-cd5cf',
    storageBucket: 'servexpert-cd5cf.appspot.com',
    iosClientId: '249654500838-p7u1c7mfrna78ooog2ldhg5v4opvm245.apps.googleusercontent.com',
    iosBundleId: 'com.servexpert.servExpertWebclient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmSUW179OYIL96fg4OaEoNXrkusmypeAM',
    appId: '1:249654500838:ios:42e372d76e8a8e3c614a27',
    messagingSenderId: '249654500838',
    projectId: 'servexpert-cd5cf',
    storageBucket: 'servexpert-cd5cf.appspot.com',
    iosClientId: '249654500838-p7u1c7mfrna78ooog2ldhg5v4opvm245.apps.googleusercontent.com',
    iosBundleId: 'com.servexpert.servExpertWebclient',
  );
}
